{
  "name": "Lock Threads",
  "on": {
    "schedule": [
      {
        "cron": "0 1 * * *"
      }
    ],
    "workflow_dispatch": null
  },
  "permissions": {
    "issues": "write",
    "pull-requests": "write"
  },
  "concurrency": {
    "group": "lock"
  },
  "jobs": {
    "action": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "dessant/lock-threads@v3"
        }
      ]
    }
  }
}
