# Very similar to the release build.
# Feel free to merge those into a single yaml
{
  'name': 'Manual Build',
  'on': ['workflow_dispatch'],
  'jobs':
    {
      'build-valetudo':
        {
          'runs-on': 'ubuntu-latest',
          'steps':
            [
              { 'uses': 'actions/checkout@v3' },
              {
                'name': 'Use Node.js 16.x',
                'uses': 'actions/setup-node@v3',
                'with': { 'node-version': '16.x' },
              },
              { 'name': 'Install', 'run': 'npm ci' },
              {
                'name': 'Generate OpenAPI Docs',
                'run': 'npm run build_openapi_schema',
              },
              {
                'name': 'Build Valetudo frontend',
                'run': 'npm run build --workspace=frontend',
              },
              {
                'name': 'Build Valetudo armv7',
                'run': 'npm run build_armv7 --workspace=backend',
              },
              {
                'name': 'Build Valetudo armv7 lowmem',
                'run': 'npm run build_armv7_lowmem --workspace=backend',
              },
              {
                'name': 'Build Valetudo aarch64',
                'run': 'npm run build_aarch64 --workspace=backend',
              },

              {
                'name': 'Upload armv7 build',
                'uses': 'actions/upload-artifact@v3',
                'with':
                  {
                    'name': 'valetudo-armv7',
                    'path': './build/armv7/valetudo',
                  },
              },
              {
                'name': 'Upload armv7 lowmem build',
                'uses': 'actions/upload-artifact@v3',
                'with':
                  {
                    'name': 'valetudo-armv7-lowmem',
                    'path': './build/armv7/valetudo-lowmem',
                  },
              },
              {
                'name': 'Upload aarch64 build',
                'uses': 'actions/upload-artifact@v3',
                'with':
                  {
                    'name': 'valetudo-aarch64',
                    'path': './build/aarch64/valetudo',
                  },
              },

              {
                'name': 'UPX-compress valetudo binaries',
                'run': 'npm run upx',
              },
              {
                'name': 'Upload armv7 upx build',
                'uses': 'actions/upload-artifact@v3',
                'with':
                  {
                    'name': 'valetudo-armv7.upx',
                    'path': './build/armv7/valetudo.upx',
                  },
              },
              {
                'name': 'Upload armv7 lowmem upx build',
                'uses': 'actions/upload-artifact@v3',
                'with':
                  {
                    'name': 'valetudo-armv7-lowmem.upx',
                    'path': './build/armv7/valetudo-lowmem.upx',
                  },
              },
              {
                'name': 'Upload aarch64 upx build',
                'uses': 'actions/upload-artifact@v3',
                'with':
                  {
                    'name': 'valetudo-aarch64.upx',
                    'path': './build/aarch64/valetudo.upx',
                  },
              },

              {
                'name': 'Build manifest',
                'run': 'npm run build_release_manifest',
              },
              {
                'name': 'Upload manifest',
                'uses': 'actions/upload-artifact@v3',
                'with':
                  {
                    'name': 'valetudo_release_manifest.json',
                    'path': './build/valetudo_release_manifest.json',
                  },
              },
            ],
        },
    },
}
