# Very similar to the release build.
{
  'name': 'Nightly build',
  'on': {
    'schedule': [
      {
        'cron': '16 2 * * *'
      }
    ],
    'workflow_dispatch': null
  },
  'jobs':
    {
      'nightly_build':
        {
          'runs-on': 'ubuntu-latest',
          'if': "github.repository_owner == 'Hypfer'",
          'steps':
            [
              {
                'uses': 'actions/checkout@v4',
                'with': {
                  'fetch-depth': 0
                }
              },
              {
                'name': 'Use Node.js 20.x',
                'uses': 'actions/setup-node@v4',
                'with': { 'node-version': '20.x' },
              },
              { 'name': 'Install', 'run': 'npm ci' },
              {
                'name': 'Generate OpenAPI Docs',
                'run': 'npm run build_openapi_schema',
              },
              {
                'name': 'Build Valetudo frontend',
                'run': 'npm run build --workspace=frontend',
              },
              {
                'name': 'Build Valetudo',
                'run': 'npm run build --workspace=backend',
              },
              {
                'name': 'UPX-compress valetudo binaries',
                'run': 'npm run upx',
              },
              {
                'name': 'Generate changelog',
                'run': 'npm run generate_nightly_changelog',
              },
              {
                'name': 'Build manifest',
                'run': 'npm run build_release_manifest nightly',
              },
              {
                'name': 'Push binaries to nightly repo',
                'id': 'push_directory',
                'uses': 'hypfer/github-action-push-to-another-repository@v1.3',
                'env': {
                  'API_TOKEN_GITHUB': '${{ secrets.API_TOKEN_GITHUB }}'
                },
                'with': {
                  'source-directory': 'build',
                  'destination-github-username': 'ValetudoBot',
                  'destination-repository-name': 'valetudo-nightly-builds',
                  'destination-repository-username': 'hypfer',
                  'user-email': 'github_valetudo_bot@hypfer.de',
                  'target-branch': 'master'
                }
              }
            ],
        },
    },
}
