{
  'name': 'Node.js CI',
  'on': ['push', 'pull_request'],
  'jobs':
    {
      'build':
        {
          'runs-on': 'ubuntu-latest',
          'strategy': { 'matrix': { 'node-version': ['16.x'] } },
          'steps':
            [
              { 'uses': 'actions/checkout@v2' },
              {
                'name': 'Use Node.js ${{ matrix.node-version }}',
                'uses': 'actions/setup-node@v3',
                'with': { 'node-version': '${{ matrix.node-version }}' },
              },
              { 'run': 'npm ci' },
              {
                'name': 'Generate OpenAPI Docs',
                'run': 'npm run build_openapi_schema',
              },
              { 'run': 'npm run ts-check --workspace={frontend,backend}' },
              { 'run': 'npm run lint --workspace={frontend,backend}' },
              { 'run': 'npm run build --workspace=frontend' },
              { 'run': 'npm run build --workspace=backend' },
              { 'run': 'npm test --workspace=backend', 'env': { 'CI': true } },
            ],
        },
    },
}
