name: Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm ci
    - name: Build Valetudo armv7
      run: npm run build
    - name: Build Valetudo armv7 lowmem
      run: npm run build_armv7_lowmem
    - name: Build Valetudo aarch64
      run: npm run build_aarch64
    - name: UPX-compress valetudo binaries
      run: npm run upx
    - name: Upload Valetudo armv7
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/armv7/valetudo
        asset_name: valetudo-armv7
        asset_content_type: binary/octet-stream
    - name: Upload Valetudo armv7.upx
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/armv7/valetudo.upx
        asset_name: valetudo-armv7.upx
        asset_content_type: binary/octet-stream
    - name: Upload Valetudo armv7 lowmem
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/armv7/valetudo_lowmem
        asset_name: valetudo-armv7-lowmem
        asset_content_type: binary/octet-stream
    - name: Upload Valetudo armv7 lowmem.upx
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/armv7/valetudo_lowmem.upx
        asset_name: valetudo-armv7-lowmem.upx
        asset_content_type: binary/octet-stream
    - name: Upload Valetudo aarch64
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/aarch64/valetudo
        asset_name: valetudo-aarch64
        asset_content_type: binary/octet-stream
    - name: Upload Valetudo aarch64.upx
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/aarch64/valetudo.upx
        asset_name: valetudo-aarch64.upx
        asset_content_type: binary/octet-stream

